### ISSUE TITLE
Fail to build OpenJDK with MMTk on lxr branch

### ISSUE THREAD

**Issue by jiaweixiao** [wenyuzhao/mmtk-core#68]
Hi,  
I am following instructions in https://github.com/wenyuzhao/mmtk-core/tree/lxr#getting-started to build LXR GC.  
Here is the directory structure of this project:
```bash
/home/test/openjdks/mmtk-lxr/
├─ mmtk-openjdk/
├─ openjdk/
└─ mmtk-core/
```
-----
Steps before 3.(ii) went well, but errors occurred after running this command:
```bash
GC_FEATURES=lxr make CONF=linux-x86_64-normal-server-release THIRD_PARTY_HEAP=$PWD/../mmtk-openjdk/openjdk images
```
The output is:
```bash
Note: Command line contains non-control variables:
* THIRD_PARTY_HEAP=/home/test/openjdks/mmtk-lxr/openjdk/../mmtk-openjdk/openjdk
Make sure it is not mistyped, and that you intend to override this variable.
'make help' will list known control variables.

Building target 'images' in configuration 'linux-x86_64-normal-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Creating hotspot/variant-server/tools/adlc/adlc from 13 file(s)
Compiling 2 files for BUILD_JVMTI_TOOLS
Compiling 1 files for BUILD_JFR_TOOLS
Parsing 2 properties into enum-like class for jdk.compiler
Compiling 7 properties into resource bundles for jdk.jshell
Compiling 12 properties into resource bundles for jdk.jdeps
Compiling 13 properties into resource bundles for jdk.javadoc
Compiling 19 properties into resource bundles for jdk.compiler
Compiling 117 files for BUILD_java.compiler.interim
Compiling 394 files for BUILD_jdk.compiler.interim
Creating support/modules_libs/java.base/server/libjvm.so from 999 file(s)
Creating hotspot/variant-server/libjvm/gtest/libjvm.so from 108 file(s)
Creating hotspot/variant-server/libjvm/gtest/gtestLauncher from 1 file(s)
cd /home/test/openjdks/mmtk-lxr/openjdk/../mmtk-openjdk/openjdk/../mmtk && cargo --version && cargo build --release --target x86_64-unknown-linux-gnu --features lxr
cargo 1.72.0 (103a7ff2e 2023-08-15)
error: none of the selected packages contains these features: lxr
make[3]: *** [/home/test/openjdks/mmtk-lxr/openjdk/../mmtk-openjdk/openjdk/CompileThirdPartyHeap.gmk:72: /home/test/openjdks/mmtk-lxr/openjdk/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/server/libmmtk_openjdk.so] Error 101make[3]: *** Waiting for unfinished jobs....
Compiling 299 files for BUILD_jdk.javadoc.interim
make[2]: *** [make/Main.gmk:272: hotspot-server-libs] Error 2
make[2]: *** Waiting for unfinished jobs....

ERROR: Build failed for target 'images' in configuration 'linux-x86_64-normal-server-release' (exit code 2)

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [/home/test/openjdks/mmtk-lxr/openjdk/make/Init.gmk:308: main] Error 2
make: *** [/home/test/openjdks/mmtk-lxr/openjdk/make/Init.gmk:186: images] Error 2
```
-----
I also try to remove the environment variable:
```bash
make CONF=linux-x86_64-normal-server-release THIRD_PARTY_HEAP=$PWD/../mmtk-openjdk/openjdk images
```
The build succeed, and tests on plan `LXR`, `SemiSpace` and `MarkSweep`  with fop in dacapo-23.11-chopin passed:
```bash
/home/test/openjdks/mmtk-lxr/openjdk/build/linux-x86_64-normal-server-release/images/jdk/bin/java -server -XX:+UseThirdPartyHeap -XX:ThirdPartyHeapOptions=plan=LXR -jar dacapo-23.11-chopin.jar fop

/home/test/openjdks/mmtk-lxr/openjdk/build/linux-x86_64-normal-server-release/images/jdk/bin/java -server -XX:+UseThirdPartyHeap -XX:ThirdPartyHeapOptions=plan=SemiSpace -jar dacapo-23.11-chopin.jar fop

/home/test/openjdks/mmtk-lxr/openjdk/build/linux-x86_64-normal-server-release/images/jdk/bin/java -server -XX:+UseThirdPartyHeap -XX:ThirdPartyHeapOptions=plan=MarkSweep -jar dacapo-23.11-chopin.jar fop
```
However, test on plan `MarkCompact` failed, and the output is:
```bash
thread '<unnamed>' panicked at 'not implemented', /home/test/openjdks/mmtk-lxr/mmtk-core/src/plan/markcompact/global.rs:134:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
   3: <mmtk::plan::markcompact::global::MarkCompact<VM> as mmtk::plan::global::Plan>::schedule_collection
   4: mmtk::scheduler::controller::GCController<VM>::run
   5: start_control_collector
   6: _ZN6Thread8call_runEv
             at /home/test/openjdks/mmtk-lxr/openjdk/src/hotspot/share/runtime/thread.cpp:402:12
   7: thread_native_entry
             at /home/test/openjdks/mmtk-lxr/openjdk/src/hotspot/os/linux/os_linux.cpp:826:19
   8: start_thread
             at /build/glibc-BHL3KM/glibc-2.31/nptl/pthread_create.c:477:8
   9: clone
             at /build/glibc-BHL3KM/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
Could you please help me?
Thanks

**Comment by wenyuzhao** [comment]
Hi sorry for the late reply. Currently in the lxr branch, all the plans other than LXR should considered as faulty. I completely rewrote the memory allocator / mapper a few months ago and they can only work with LXR at the moment.

If you'd like to try other GC plans, please use the upstream mmtk https://github.com/mmtk/mmtk-core. Thanks!

**Comment by jiaweixiao** [comment]
Thanks, I will try the upstream mmtk.
